### ISSUE TITLE
passed_time * passed_weight + current_time * current_weight不是很理解

### ISSUE THREAD

**Issue by edagarli** [JamesPan/orz-ops#1]
dynamic-upstream-weight.lua文件里面的
为啥0.3 ，0.7基数？

**Comment by JamesPan** [comment]
就是一个让过去的值的作用随着时间推移逐渐衰减的加权策略，0.3 和 0.7 只是我随便定的参数，想让最新值的权重稍微大一些而已

![pdf page 89 of 583 2017-02-05 21-18-40](https://cloud.githubusercontent.com/assets/1175306/22626461/c7debeb0-ebe8-11e6-8128-b539c7c6a4e5.png)

**Comment by edagarli** [comment]
soga

**Comment by edagarli** [comment]
还有个问题哈，upstream_response_time这个其实我还没完全明白是什么时间。因为一个系统的接口有块有慢，平均时间的话会不会更好？
